# Generated by Django 4.0.3 on 2023-01-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_comp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usr',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
